name: Practise Project 1
on: [push]
jobs:
  Deployjob:
    runs-on: ubuntu-latest
    steps:
      - name: load code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: |
          npm run lint
          npm run test
          npm run build
      - name: echo message
        run: echo "all ran"
